apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-env
  namespace: movieapp
data:
  APP_ENV: "production"
  # API_URL for external access (browser needs external URL)
  API_URL: "http://16.16.89.200:31461"

