apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: movieapp
type: Opaque
stringData:
  # Replace these with your actual values
  # You can also use: kubectl create secret generic backend-secrets --from-literal=MONGODB_URI='your-uri' --namespace=movieapp
  MONGODB_URI: "mongodb+srv://movieapp:btth1122@ahmedcluster.rdukguv.mongodb.net/moviedb?retryWrites=true&w=majority&appName=ahmedcluster"
  JWT_SECRET: "secretkey@123"
  NODE_ENV: "production"
  PORT: "5000"

