apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: movieapp
  labels:
    app: backend
spec:
  type: NodePort  # Expose externally for browser access
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 31461  # External port (30000-32767 range)
    protocol: TCP
    name: http
  selector:
    app: backend

